<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Views\Shared\_Layout.cshtml.css" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Bot.Schema" Version="4.23.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PlatformManagementSystem.Application\PlatformManagementSystem.Application.csproj" />
    <ProjectReference Include="..\PlatformManagementSystem.Infrastructure\PlatformManagementSystem.Infrastructure.csproj" />
  </ItemGroup>

</Project>
